### ISSUE TITLE
F4 Error

### ISSUE THREAD

**Issue by atssada** [yanataka60/MSX_SD#1]
素晴らしい作品を公開していただきありがとうございます！

まねで楽しくことしかできないものとして、恥ずかしながら質問させていただきます。

Call sdirコマンドで

F4 Error

が出ますが、SDカードの問題ですかね？
3種類のSDカードをFAT32でフォーマットして、ルートディレクトにBatman.casを一つだけ置き、試しましたが、どれもF4 Errorでした。

**Comment by yanataka60** [comment]
F4 Errorは、MSXがArduinoへ送るコマンドがArduinoにとって想定外であることを表しています。
ひとつ考えられるケースとしてArduinoのA4、A5ピンを配線していないのではないでしょうか。
確認してみてください。

2024年2月3日(土) 18:21 Jinyong Kim ***@***.***>:

**Comment by atssada** [comment]
ご親切な説明ありがとうございます！

無事解決できました！ mm

**Comment by yanataka60** [comment]
解決できて良かったです。

2024年2月6日(火) 8:18 Jinyong Kim ***@***.***>:
